### ISSUE TITLE
Issues with the map on the Contact page

### ISSUE THREAD

**Issue by v-stamenova** [HZ-HBO-ICT/it-conference#189]
<img width="976" alt="image" src="https://github.com/HZ-HBO-ICT/it-conference/assets/77020646/439fa143-00bc-4199-b8df-4dce43bbe061">

* The page is not responsive as well

**Comment by TimKardol** [comment]
Fixed one issue by adding the complete url to the api key allowed websites in my maps api dashboard.

**Comment by TimKardol** [comment]
Fixed noApiKey error by adding api key to .env in the production folder.

**Comment by TimKardol** [comment]
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/54664131/705ee72b-887b-4118-b6c0-0e292a517950)

Current errors on localhost

**Comment by TimKardol** [comment]
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/54664131/eca75817-dd71-465e-ad9d-e59c33f3f234)

Current errors on production

**Comment by TimKardol** [comment]
@v-stamenova Might need to go through this together.

**Comment by v-stamenova** [comment]
> @v-stamenova Might need to go through this together.

Yeah, today?

**Comment by daphneheertjes** [comment]
Tim, since you asked, I got this message through the firefox console. It works as a charm in google chrome 

Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://www.weareinittogether.nl/contact 

Uncaught (in promise) TypeError: a.getDiv() is undefined
    ona https://maps.googleapis.com/maps-api-v3/api/js/54/6-beta/intl/nl_ALL/map.js:2
    xa https://maps.googleapis.com/maps-api-v3/api/js/54/6-beta/intl/nl_ALL/map.js:118

This is what I found in response...it might help  https://stackoverflow.com/questions/35288250/google-maps-javascript-api-referernotallowedmaperror

**Comment by TimKardol** [comment]
Seems this has been fixed for the most part. Thing is that most of these issues happen because of client side restriction put up by browsers and adblockers. I'll leave it open for future work.

**Comment by dwaard** [comment]
We could use https://www.openstreetmap.org instead
