### ISSUE TITLE
Rework: Database rework and planning

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#363]

**Comment by TimKardol** [comment]
@v-stamenova I talked with Daphne and Frans. We can migrate the production databases when we are ready with the new design. We talked about making a database (or was it migration mapping) so people won't have to register again. I think this is a good plan and should be easily done with a migration we run. Probably involve Elio and Frans to figure this out.

**Comment by v-stamenova** [comment]
> @v-stamenova I talked with Daphne and Frans. We can migrate the production databases when we are ready with the new design. We talked about making a database (or was it migration mapping) so people won't have to register again. I think this is a good plan and should be easily done with a migration we run. Probably involve Elio and Frans to figure this out.

Will start researching. We need to discuss as well if we're going to keep only the participants or the company representatives as well, because if we keep the latter as well there are more details to figure out like - are we removing the company; do we remove all users associated with the company and so on.
